### ISSUE TITLE
ImportError: No module named osmosdr

### ISSUE THREAD

**Issue by Ossie76** [madengr/ham2mon#14]
Hi,

I got this error, not sure how to solve things.

Traceback (most recent call last):
  File "./ham2mon.py", line 9, in <module>
    import scanner as scnr
  File "/home/abels/SDR/ham2mon/apps/scanner.py", line 9, in <module>
    import receiver as recvr
  File "/home/abels/SDR/ham2mon/apps/receiver.py", line 10, in <module>
    import osmosdr
ImportError: No module named osmosdr

Did install http://sdr.osmocom.org/trac/wiki/GrOsmoSDR for so far.

Installed gnuradio and dev files under ubuntu willy.

Maybe it has to do with:
- ######################################################

-- # Gnuradio disabled components                        

-- ######################################################

--   \* Python support
--   \* Osmocom IQ Imbalance Correction
--   \* sysmocom OsmoSDR

used: sudo cmake ../ -DENABLE_OSMOSDR=ON -DENABLE_PYTHON=ON
this gave some erros.

What libs and or packages do i exactly need on my system ?

Regards.

**Comment by madengr** [comment]
- # Gnuradio disabled components 
  This says osmosdr is probably not finding GNU Radio libraries.
  Did you build osmosdr after you installed GNU Radio?  Did you run a "sudo ldconfig" after installing GNU Radio?

**Comment by Ossie76** [comment]
Seems to work now after some struggling.

Needed some more packages like another SWIG and DOXYGEN version.
After that deleted gr-osmosdr dir. and cloned it again with git, and configuring.

Now to see if i can scan some freqs. and get a signal and sound with the RTL-SDR.
