### ISSUE TITLE
Information Request:  Setting Auto Gain With RTL Driver

### ISSUE THREAD

**Issue by john-** [madengr/ham2mon#16]
This is probably not a ham2mon question but here it goes...

I want start ham2mon and pass argument to rtl driver to have it use AGC.  I have tried things like this and it is not clear to me that it is set:  -a "rtl=0,gain_mode=Automatic"

I haven't dug too deep into to code but expect ham2mon just passes this like other settings that I know work.

Any input would be appreciated!

Thanks,

John

**Comment by madengr** [comment]
If it passes one argument, it passes them all.  I guess the question is if the osmocom implements the AGC, or properly configures the rtl device.  I'm not familiar with those devices.

**Comment by john-** [comment]
Good point.   I will look into osmocom driver as this is not related to ham2mon.
