### ISSUE TITLE
Information Request:   Gain Names and Airspy

### ISSUE THREAD

**Issue by john-** [madengr/ham2mon#30]
I am working with an Airspy Mini and getting an understanding of gain controls that are available.   From my review of gnuradio source it looks like the gain controls a particular brand of SDR has varies.   From what i have seen ham2mon doesn't currently take this into account.  So in case of Airspy the BB gain control in ham2mon doesn't do anything which makes sense as it has a Mix gain setting instead.   The other 2 gain controls seem to do right thing (not 100% sure yet).

Here is a point in gnuradio where difference is:
https://github.com/osmocom/gr-osmosdr/blob/4d83c6067f059b0c5015c3f59f8117bbd361e877/lib/airspy/airspy_source_c.cc#L446
https://github.com/osmocom/gr-osmosdr/blob/4d83c6067f059b0c5015c3f59f8117bbd361e877/lib/hackrf/hackrf_source_c.cc#L563

If the above seems off let me know.

Question:  To support Airspy do we add another gain (Mix) to ham2mon?   Should the design be changed to support something more dynamic?

John

**Comment by john-** [comment]
So I took a stab at addressing this:

https://github.com/madengr/ham2mon/compare/master...john-:gain_changes_squashed

- The gain elements supported by a particular driver are dynamically displayed in the ham2mon gui
- As the gains vary the keyboard shortcuts now reference them by position and not name.
- The command line parameters should be unchanged as well as the behavior ham2mon uses uniquely treat the RF gain element.
- This has gone through basic testing with RTL, HackRF and Airspy Mini.   USRP and other hardware are untested.
- The Airspy does not use dB reference for gain values and instead uses indices.
- There has been no performance verification yet but nothing seems too crazy.
- The overall effect should mimic what appears in gqrx gui for a particular SDR.

Feel free to use github feature to create issues for anything in the code and comment here for general feedback (this could be way off base or I missed something big)

**Comment by madengr** [comment]
I can't run it as I have moved to GR 3.8 and Python 3, thus ham2mon will eventually need to be moved to Python 3.  Also, gr-osmosdr won't build with Python 3.

**Comment by john-** [comment]
Closing this.  It can be looked at with move to Python 3.
