### ISSUE TITLE
Airspy Mini on SBC (Pi compatible) / ham2mon performance tweaks?

### ISSUE THREAD

**Issue by john-** [madengr/ham2mon#32]
I can use airspy_rx to stream data from Airspy 3MSPS (lowest supported rate).  Also streams fine at 6MSPS.  With ham2mon gnuradio indicates there are overruns.   There is lag in UI and audio files sound like they are sped up.   Can anything be done with the gnuradio flowgraph in ham2mon help improve performance?   Yes, this is pretty vague so if more info is needed let me know.

**Comment by madengr** [comment]
Did you run volk_profile ?

**Comment by john-** [comment]
Thanks for mentioning volk_profile as I didn't know it existed.   It not only has improved things but was very satisfying to use!

It has gotten ham2mon working to the point I can look at some things unrelated to the performance issue.

**Comment by john-** [comment]
In case it helps someone:  Odroid XU4 with ham2mon works without overruns when:

- volk_profile us used to optimize gnuradio
- 2 demodulators are used (-n 2)

With 3 simultaneous demods overruns occur which causes a "static" in the recorded audio.
