### ISSUE TITLE
ham2mon error

### ISSUE THREAD

**Issue by k0ue** [madengr/ham2mon#6]
I receive the following error message when I try to run ham2mon.py in python2.7 with gnuradio 3.7.5:

cubbedge@linux-wxfr:~/ham2mon/ham2mon-60f9358ca526fc8542f3c2fe5ca61dcacb340c44/apps> ./ham2mon.py -a "rtl" -n 4 -f 145E6 -r 2E6 -g 20 -s -40 -v 0 -t 30 -w  
Traceback (most recent call last):  
  File "./ham2mon.py", line 130, in <module>  
    curses.wrapper(main)  
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper  
    return func(stdscr, _args, *_kwds)  
  File "./ham2mon.py", line 54, in main  
    freq_correction, record, lockout_file_name)  
  File "/home/cubbedge/ham2mon/ham2mon-60f9358ca526fc8542f3c2fe5ca61dcacb340c44/apps/scanner.py", line 68, in **init**  
    hw_args, freq_correction, record)  
  File "/home/cubbedge/ham2mon/ham2mon-60f9358ca526fc8542f3c2fe5ca61dcacb340c44/apps/receiver.py", line 460, in **init**  
    integrate_ff = blocks.integrate_ff(100, fft_length)  
  File "/usr/lib64/python2.7/site-packages/gnuradio/blocks/blocks_swig3.py", line 592, in make  
    return _blocks_swig3.integrate_ff_make(_args, *_kwargs)  
TypeError: integrate_ff_make() takes at most 1 argument (2 given)  
Reattached kernel driver  
cubbedge@linux-wxfr:~/ham2mon/ham2mon-60f9358ca526fc8542f3c2fe5ca61dcacb340c44/apps>    

Any ideas?

Skip Cubbedge

**Comment by madengr** [comment]
Can you run the GRC flow example?

**Comment by madengr** [comment]
You'll probably need GR 3.7.8, as it seems the integrate_ff in 3.7.5 does not accept a vector.

**Comment by john-** [comment]
For sure use 3.7.8.  Even though readme explicitly says this version I 
initially tried 3.7.7 and there was an error (not sure if it was the 
same or not).

John

**Comment by Dygear** [comment]
There is another project that has this issue, I wonder how far upstream Header Only / Blank (And I'm going to start calling these HOBs) this issue goes as OP25's scope.py application has this same issue. I assumed it was a demod error all of the time as the files never included a talk group id as required by the spec.

**Comment by k0ue** [comment]
Am having trouble now installing 3.7.8 -- qt seems to be missing when I run grc.  When I get it fixed will try the flow graph and ham2mon again.

**Comment by k0ue** [comment]
I can run both flow graphs in grc, but when I run ham2mon.py in a terminal window, I get an error,

ImportError: libgnuradio-runtime-3.7.5.1.so.0.0.0: cannot open shared object file: No such file or directory

I am running gnuradio 3.7.8rc1 in OpenSuse.

**Comment by madengr** [comment]
Try running:
sudo ldconfig

**Comment by k0ue** [comment]
I ran sudo ldconfig and got the same result.

**Comment by madengr** [comment]
It's still looking for the 3.7.5 library, but you installed 3.7.8.  I don't know how to fix that.  Might want to ask on the GR mailing list.  Did you build GR from source?  3.7.8 was released 2 weeks ago (3.7.8rc1) is outdated, but it should still work as that is what I used to write it.

**Comment by madengr** [comment]
Was 3.7.5 installed from a package manager, and 3.7.8 from source?  If so, maybe the library search path does not have the location of the compiled libraries.  In fedora I had to create /etc/ld.so.conf.d/userlocal.conf which contains /usr/local/lib and /usr/local/lib64

You may have to point it to wherever GR installed it's libraries.

**Comment by k0ue** [comment]
I think I found the problem.  I reinstalled 3.7.8 from source, and then updated gr-osmosdr to the latest version via github.  Everything now works fine with my rtl dongle.

Thanks for your help!  I look forward to experimenting with your fine radio.
